name: CICD
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1

      - name: Yarn Install
        uses: nuxt/actions-yarn@master
        with:
          args: install

      - name: AWS CDK Deploy
        uses: MikeBild/aws-cdk-js-github-action@1.0.0
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
